info:
  app:
    name: ${project.name}
    description: ${project.description}
    artifactId: ${project.artifactId}
    version: ${project.version}
management:
  context-path: /manage
spring:
  thymeleaf:
    cache: false

---

spring:
  profiles: embedded
server:
  port: 9080
  context-path: /aui