i18n:
  cache: 10
  encoding: UTF-8
  prefix: classpath:/localization/
  names:
    - gui-labels
    - gui-messages
info:
  app:
    name: ${project.name}
    description: ${project.description}
    artifactId: ${project.artifactId}
    version: ${project.version}
management:
  context-path: /manage
spring:
  data:
    mongodb:
      uri: mongodb://localhost/aui
  thymeleaf:
    cache: false
---

spring:
  profiles: embedded
server:
  port: 9080
  context-path: /aui

---

spring:
  profiles: production
  thymeleaf:
    cache: true